Use setup/teardown for DAO tests, truncate tables instead of seeding
RHEnVision/provisioning-backend pull request #149
Opened 2022-08-10 11:21 UTC by lzap

There are two commits in this PR.

The first one improves the DAO tests in general:

* Generic functions were moved into main_test.go and are not exported.
* There are now global `setup` and `teardown` functions and `setupPubkey` etc functions in each file for more specific setup code.
* All setup functions were renamed and broken down into `dbDrop`, `dbMigrate` and `dbSeed` to better reflect what they do.
* Error handling was vastly simplified - for fatal error states (cannot connect to DB, cannot migrate or seed) using `panic` is completely fine because this is a fatal state anyway. Setup functions themselves no longer return errors which makes the code longer due to use of panic keyword.
* Teardown functions are called via `defer`.

The second commit then switches from migrating the database for each test to more straightforward approach - the database is seeded just once and then every test all tables are truncated. This makes DAO tests faster, for me it dropped from 6 seconds down to 4.3 seconds. It's not much, but this feels cleaner.

2022-08-10 15:03 UTC, avitova requested changes
I can't test this right now, if this works, I agree. Thank you for refactoring reservation tests. We just have to make sure that we are consistent in error messages, so that we are consistent.

2022-08-11 11:03 UTC, avitova commented
Update pubkey test panics with
```
panic: runtime error: slice bounds out of range [:-1]
	panic: runtime error: slice bounds out of range [:-1]

```

2022-08-11 12:23 UTC, lzap commented
Please rebase on top of main, I fixed this overlook in the logging function. I will shortly rebase this PR.

2022-08-11 12:25 UTC, lzap commented
Rebased!

2022-08-11 13:41 UTC, adiabramovitch commented on cmd/dao_tests/pubkey_test.go
> +		t.Errorf("Create pubkey test failed. %s", err)
You are checking UpdatePubkey, so maybe change the error msg?

2022-08-11 13:42 UTC, adiabramovitch commented on cmd/dao_tests/pubkey_test.go
> +	err := pkDao.Create(ctx, createPk())
and I guess this is supposed to be update?

2022-08-11 13:49 UTC, adiabramovitch approved these changes

2022-08-11 13:50 UTC, merged