Add Sources service and client
RHEnVision/provisioning-backend pull request #31
Opened 2022-06-01 13:43 UTC by adiabramovitch

Thanks for the contribution, take a moment to read our contributing and security guidelines:

**Checklist**
- [ ] https://github.com/RHEnVision/provisioning-backend#contributing
- [ ] https://github.com/RedHatInsights/secure-coding-checklist
 
depends on #9

2022-06-02 11:24 UTC, lzap commented
Let's just have a call with Sources API for their advice on what exactly are we supposed to keep in our DB. I would like to put as high resistance as we can to avoid storing duplicate data, maybe we can get away just with calling their API and in-memory LUR cache.

2022-06-13 10:57 UTC, ezr-ondrej commented
linter doesn't like extra empty lines https://pastebin.com/5V34jZPk :facepalm:
If it is not easy to get rid of those while generating, I'll find out how to not check the autogenerated files.

2022-06-13 13:48 UTC, adiabramovitch commented
> linter doesn't like extra empty lines https://pastebin.com/5V34jZPk facepalm If it is not easy to get rid of those while generating, I'll find out how to not check the autogenerated files.

I just didn't have goimports so it didn't correct it :)

2022-06-13 15:00 UTC, lzap requested changes
Its allright but Makefile does not work.

I suggest to add all generated files (*.gen.go) to be skipped by all linters.

2022-06-14 06:43 UTC, adiabramovitch commented on Makefile
> +	generate-sources-client
Thank you for noticing, I will change it to the syntax you have done in your PR.

2022-06-14 06:58 UTC, adiabramovitch commented on Makefile
> +	oapi-codegen -config ./configs/sources_config.yml ./configs/sources_api.json
so here If I want it to work for sources as well it is supposed to b like that? 

```golang
.PHONY: update-clients
update-clients:
	wget -O ./configs/ib_api.yaml -qN https://raw.githubusercontent.com/osbuild/image-builder/main/internal/v1/api.yaml
	wget -O ./configs/sources_api.json -qN https://raw.githubusercontent.com/RedHatInsights/sources-api-go/main/public/openapi-3-v3.1.json 

generate-clients: internal/clients/image_builder/client.gen.go internal/clients/sources/sources_client.gen.go

internal/clients/sources/sources_client.gen.go: configs/sources_config.yml configs/sources_api.json

internal/clients/image_builder/client.gen.go: configs/ib_config.yaml configs/ib_api.yaml
```

2022-06-14 12:11 UTC, ezr-ondrej commented on Makefile
> +	oapi-codegen -config ./configs/sources_config.yml ./configs/sources_api.json
yup, I feel like that is correct :)

2022-06-14 12:14 UTC, lzap commented on Makefile
> +	oapi-codegen -config ./configs/sources_config.yml ./configs/sources_api.json
Yeah does not look great, I can improve later (with variables perhaps). Or if you like, you can introduce a variable to replace all occurrences of `internal/clients` so its a bit shorter and more readable:

```Makefile
CLIENTS_DIR := internal/clients

$(CLIENTS_DIR)/image_builder/client.gen.go: configs/ib_config.yaml configs/ib_api.yaml
# etc etc
```

2022-06-14 12:14 UTC, ezr-ondrej approved these changes
The config structure feels bit weird as `RestEnpoints` is hard to understand and we have double nesting for just two properties, but I guess that can be improved as we go ^_^

2022-06-14 12:16 UTC, lzap commented on internal/config/main_config.go
> +	RestEndpoints struct {
Yeah renaming is easy in Go... I like that we at least have a common struct for these.

2022-06-14 12:17 UTC, lzap approved these changes
Nice.

2022-06-14 12:17 UTC, lzap commented on internal/config/main_config.go
> +var SourcesURL = &config.RestEndpoints.Sources.URL
I would only export RestEndpoints here to follow the pattern, but it's okay.

    var RestEndpoints = &config.RestEndpoints

2022-06-14 12:17 UTC, merged