fix(HMSPROV-392): Check if image is an original or a shared one
RHEnVision/provisioning-backend pull request #351
Opened 2023-01-02 14:55 UTC by adiabramovitch

Images can be shared to different regions in Image Builder. 
shared images are not visible under /compose endpoint in IB but under /clone.
Therefore if an image is not visible under /compose,  before erroring out we should search for the image under /clone. 
Only if the image is not preset neither under compose nor clone we should error out with the message that the image is not available.

2023-01-02 16:06 UTC, ezr-ondrej reviewed
Few nits, but nothing major.
Given we are calling Image builder twice now, I'd think about adding OpenTelemetry tracing around it and measure those calls in their own span, but that should be (if we decide to do it) a follow up anyway :)

2023-01-03 08:02 UTC, adiabramovitch commented
> Few nits, but nothing major. Given we are calling Image builder twice now, I'd think about adding OpenTelemetry tracing around it and measure those calls in their own span, but that should be (if we decide to do it) a follow up anyway :)

Fixed and added :)

2023-01-03 10:31 UTC, lzap requested changes
Two error handling comments.

2023-01-03 10:31 UTC, lzap commented on internal/clients/http/image_builder/image_client.go
> +			return nil, fmt.Errorf("could not find image neither in compose nor in clones %w", err)
Mind adding colon, error could be misleading without it:

```suggestion
			return nil, fmt.Errorf("could not find image neither in compose nor in clones: %w", err)
```

2023-01-03 10:31 UTC, lzap commented on internal/clients/http/image_builder/image_client.go
> +			return nil, fmt.Errorf("fetch image status call: %w", http.ComposeNotFoundErr)
This is `checkClone` so:

```suggestion
			return nil, fmt.Errorf("fetch image status call: %w", http.CloneNotFoundErr)
```

2023-01-03 13:54 UTC, lzap approved these changes
Leaving this on @amirfefer since he is working on this IIRC.

2023-01-05 22:24 UTC, amirfefer approved these changes
Looks good, tested multiple image's clones 
Thanks @adiabramovitch 👍

2023-01-05 22:25 UTC, merged