feat(HMS-1773): Add IPV4 to GCP instance desc
RHEnVision/provisioning-backend pull request #526
Opened 2023-05-15 09:52 UTC by adiabramovitch

2023-05-15 16:05 UTC, lzap requested changes
That was my conclusion too when I was adding public IP to insights-core, only IPv4 is available at this point.

Looks great, few nitpicks here and there but it does the job nicely. The ID being string is ugly but as long as we want to reuse the type for other clouds I think this is fine. It is only informative at this point, so not problem.

2023-05-16 02:36 UTC, mshriver commented
/retest

2023-05-16 06:44 UTC, adiabramovitch commented on internal/clients/http/gcp/gcp_client.go
> +		instanceDesc.PublicIPv4 = *n.AccessConfigs[0].NatIP
right
Can we assume we only have one NetworkInterface for now? and do something like this by verifying it was allocated: 
```golang
	if len(instance.NetworkInterfaces) > 0 {
		inter := instance.NetworkInterfaces[0]
		instanceDesc.ID = instanceId
		if len(inter.AccessConfigs) > 0 {
			instanceDesc.PublicIPv4 = *inter.AccessConfigs[0].NatIP
		}
	}
```

2023-05-31 08:19 UTC, lzap requested changes
One dereferencing comment, please rebase (not caused by the logger refactoring I believe).

2023-05-31 08:19 UTC, lzap commented on internal/clients/http/gcp/gcp_client.go
> +			instanceDesc.PublicIPv4 = *n.AccessConfigs[0].NatIP
I still have the initial concern, you dereference something that might be `nil`. This needs to be:

```go
if n.AccessConfigs[0] != nil {
  instanceDesc.PublicIPv4 = *n.AccessConfigs[0].NatIP
}
```

2023-05-31 13:08 UTC, lzap approved these changes
Perfect work, thank you.

2023-05-31 13:08 UTC, merged