feat(HMS-729): Reservations cleanup
RHEnVision/provisioning-backend pull request #634
Opened 2023-08-08 14:37 UTC by avitova

Be careful with testing this. This will, by default, delete your reservations older than one year every one hour.

Configurable database cleanup. The default is deleting reservations older than one year every hour. I think we could maybe **improve** this by making sure users could **switch the reservation cleanup off**.
It is a bit unfortunate that the cleanenv does not offer days/years units, so we'd have to use hours even in case of a long reservation lifetime. Another thing is, that the leap year is not being taken care of. :(

2023-08-09 08:32 UTC, lzap commented
> cleanenv does not offer days/years units

Feel free to contribute, this is really quite ugly.

> leap year is not being taken care of

Maybe we can set the default value to +1 day or something like that.

2023-08-09 08:36 UTC, lzap commented on config/api.env.example
> +#     	how old reservation should be deleted, default equal to 365 days (default "8760h")
The documentation is incorrect for "duration" cases, it is not `int64` but rather `string`. Looks like a bug in cleanenv. Feel free to fix it :-)

2023-08-09 08:40 UTC, lzap commented on internal/dao/pgx/reservation_pgx.go
> +}
Note for myself: duration.String() returns "1d2h3s" format https://pkg.go.dev/maze.io/x/duration#Duration.String and postgres accepts the following https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-INTERVAL-INPUT

2023-08-09 08:41 UTC, lzap approved these changes
Perfect, I will let @ezr-ondrej to do review since he was generally against deleting anything from the database. I feel like one year is safe enough tho.

2023-08-09 11:04 UTC, ezr-ondrej requested changes
Don't get me wrong here, I'm all for this and I'm ok to do it like this, even tho we could have a Openshift job for it, to make sure we do not slow down the availability check, but it's no crucial functionality so I'm fine with that.

But **first** I'd really love to make sure, that in few months, when we hit the one year of service, we won't see some numbers go nuts.
Namely I can think of:
- usage statistics ( we calculate them from absolute numbers I believe)
- operational (and thus alerts tracking these) statistics.

I guess we should make sure that we store agregated data somewhere to fix this issue?
If we do not see any of these problems popping up, lets merge, but I'd really want to spend some time on a discussion around the consequences :)

If we have and everything is figured out, I'm fine to be told off tho :stuck_out_tongue:

2023-08-09 12:18 UTC, lzap commented
@avitova can you add a boolean flag and disable this feature by default? let’s merge this but keep it disabled, we can enable it once we have all the data stored on a safe place

2023-08-09 12:49 UTC, ezr-ondrej commented
> @avitova can you add a boolean flag and disable this feature by default? let’s merge this but keep it disabled, we can enable it once we have all the data stored on a safe place

Sounds like a great solution! :+1:

2023-08-09 14:01 UTC, avitova commented
Good idea, this solution should be sufficient.
Although I am a bit sceptical about merging this if we are not sure whether or not it is safe to use. Are we going to remember that we need to re-evaluate before using this?

2023-08-10 08:40 UTC, lzap approved these changes
TY

2023-08-10 08:48 UTC, avitova commented on internal/background/initialize.go
> +	}
Done. The rebase was done on the previous push. Not sure why does the PR check fail. :thinking:

2023-08-10 11:36 UTC, lzap commented on internal/background/initialize.go
> +	}
I just noticed one thing - this should be launched from the `stats` process not `api`

2023-08-10 13:04 UTC, avitova commented
> > cleanenv does not offer days/years units
> 
> Feel free to contribute, this is really quite ugly.
> 
Apparently, this is a consequence of Go not providing ways to convert hours to days or years. [Looks like](https://github.com/golang/go/issues/17767#issuecomment-258167205) we do not know how long days, weeks or years are:) [ParseDuration](https://pkg.go.dev/time#example-ParseDuration) only allows to parse units smaller than hours. Let's leave it as it is for now.

2023-08-10 13:06 UTC, avitova commented on internal/background/initialize.go
> +	}
Thank you for the comment, I have updated that. :+1:

2023-08-11 13:50 UTC, lzap commented
/retest

2023-08-14 09:36 UTC, lzap approved these changes
Merging thanks.

2023-08-14 09:37 UTC, lzap commented
Oh wait @ezr-ondrej needs to confirm.

2023-08-14 10:01 UTC, ezr-ondrej approved these changes
Ah sorry, did not mean to hold off this, given we are merging it disabled, I'm completely fine. The implementation itself is great :)

2023-08-14 10:01 UTC, merged